In [2]:
import os
import sys
BASE_DIR = r"C:\Users\nino.zhou\Desktop\my_project\cp_newbank_mobile_behavior"
sys.path.insert(0, BASE_DIR)

import pandas as pd
import numpy as np
from config import setting
from config import setting
import pandas as pd
import itertools
from sklearn.externals import joblib
import datetime

C:\Users\nino.zhou\anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)

In [7]:
df_train_xgboost = pd.read_csv(setting.BASE_DIR + "\data_model\data\category_xgboost.csv", index_col=0)
df_train_lstm = pd.read_csv(setting.BASE_DIR + "\data_model\data\category_lstm.csv", index_col=0)
df_train_bilstm_resnet = pd.read_csv(setting.BASE_DIR + "\data_model\data\category_bilstm_resnet.csv", index_col=0)
df_train_xgboost.shape, df_train_lstm.shape, df_train_bilstm_resnet.shape

((425359, 5), (425359, 5), (425359, 5))

In [8]:
df_train_xgboost[df_train_xgboost["category_xgboost"].notnull()]

            id  fragment_id  time_point  behavior_id  category_xgboost
57          57            1          58            0               1.0
58          58            1         146            0               1.0
59          59            1         233            0               1.0
60          60            1         322            0               1.0
61          61            1         408            0               1.0
...        ...          ...         ...          ...               ...
425296  425296         7290        4596           18              18.0
425297  425297         7290        4680           18              18.0
425298  425298         7290        4769           18              18.0
425299  425299         7290        4854           18              18.0
425300  425300         7290        4938           18              18.0

[133749 rows x 5 columns]

In [9]:
df_train_lstm[df_train_lstm["category_lstm"].notnull()]

            id  fragment_id  time_point  behavior_id  category_lstm
57          57            1   -1.693782            0            0.0
58          58            1   -1.632768            0            0.0
59          59            1   -1.572448            0            0.0
60          60            1   -1.510742            0            0.0
61          61            1   -1.451115            0            0.0
...        ...          ...         ...          ...            ...
425296  425296         7290    1.452568           18           18.0
425297  425297         7290    1.510808           18           18.0
425298  425298         7290    1.572515           18           18.0
425299  425299         7290    1.631448           18           18.0
425300  425300         7290    1.689688           18           18.0

[133749 rows x 5 columns]

In [32]:
df_merge = pd.merge(df_train_xgboost, df_train_lstm[["id", "fragment_id", "category_lstm"]], on=["id", "fragment_id"])
df_merge = pd.merge(df_merge, df_train_bilstm_resnet[["id", "fragment_id", "category_bilstm_resnet"]], on=["id", "fragment_id"])
df_merge[df_merge["category_lstm"].notnull()][300:350]

,id,fragment_id,time_point,behavior_id,category_xgboost,category_lstm,category_bilstm_resnet
1269,1269,22,1556,0,0.0,0.0,0.0
1270,1270,22,1640,0,0.0,0.0,0.0
1271,1271,22,1726,0,12.0,0.0,0.0
1272,1272,22,1815,0,0.0,0.0,0.0
1273,1273,22,1902,0,1.0,0.0,0.0
1274,1274,22,1986,0,1.0,0.0,0.0
1275,1275,22,2071,0,1.0,0.0,0.0
1276,1276,22,2162,0,1.0,0.0,0.0
1277,1277,22,2246,0,1.0,0.0,0.0
1278,1278,22,2331,0,1.0,0.0,0.0
1279,1279,22,2416,0,1.0,0.0,0.0
1280,1280,22,2500,0,1.0,0.0,0.0
1281,1281,22,2584,0,1.0,0.0,0.0
1282,1282,22,2672,0,1.0,0.0,0.0
1283,1283,22,2756,0,1.0,0.0,0.0
1284,1284,22,2840,0,1.0,0.0,0.0
1285,1285,22,2924,0,0.0,0.0,0.0
1286,1286,22,3008,0,0.0,0.0,0.0
1287,1287,22,3093,0,1.0,0.0,0.0
1288,1288,22,3178,0,1.0,0.0,0.0
1289,1289,22,3264,0,0.0,0.0,0.0
1290,1290,22,3350,0,0.0,0.0,0.0
1291,1291,22,3434,0,0.0,0.0,0.0
1292,1292,22,3520,0,0.0,0.0,0.0
1293,1293,22,3612,0,0.0,0.0,0.0
1294,1294,22,3698,0,0.0,0.0,0.0
1295,1295,22,3785,0,0.0,0.0,0.0
1296,1296,22,3870,0,0.0,0.0,0.0
1297,1297,22,3956,0,0.0,0.0,0.0
1298,1298,22,4044,0,0.0,0.0,0.0
1299,1299,22,4133,0,0.0,0.0,0.0
1300,1300,22,4219,0,0.0,0.0,0.0
1301,1301,22,4307,0,0.0,0.0,0.0
1302,1302,22,4394,0,0.0,0.0,0.0
1303,1303,22,4479,0,0.0,0.0,0.0
1304,1304,22,4564,0,0.0,0.0,0.0
1305,1305,22,4648,0,0.0,0.0,0.0
1306,1306,22,4733,0,0.0,0.0,0.0
1307,1307,22,4817,0,15.0,0.0,0.0
1308,1308,22,4903,0,0.0,0.0,0.0
1309,1309,22,4991,0,0.0,0.0,0.0
1426,1426,25,42,0,18.0,0.0,0.0
1427,1427,25,129,0,0.0,0.0,0.0
1428,1428,25,213,0,0.0,0.0,0.0
1429,1429,25,298,0,0.0,0.0,0.0
1430,1430,25,386,0,0.0,0.0,0.0
1431,1431,25,470,0,0.0,0.0,0.0
1432,1432,25,556,0,15.0,0.0,0.0
1433,1433,25,640,0,0.0,0.0,0.0
1434,1434,25,725,0,0.0,0.0,0.0

In [33]:
sr = df_merge[["category_xgboost", "category_lstm", "category_bilstm_resnet"]].iloc[1289]

values, counts = np.unique(sr, return_counts=True)
values[np.argmax(counts)]

0.0

In [43]:
def merge_category(data):
    if data.drop_duplicates().shape[0] == 3:
        return data["category_bilstm_resnet"]
    
    values, counts = np.unique(data, return_counts=True)
    return values[np.argmax(counts)]

df_merge["category_merge"] = df_merge[["category_xgboost", "category_lstm", "category_bilstm_resnet"]].apply(merge_category, axis=1)
df_merge

,id,fragment_id,time_point,behavior_id,category_xgboost,category_lstm,category_bilstm_resnet,category_merge
0,0,0,27,0,NaN,NaN,NaN,NaN
1,1,0,108,0,NaN,NaN,NaN,NaN
2,2,0,198,0,NaN,NaN,NaN,NaN
3,3,0,297,0,NaN,NaN,NaN,NaN
4,4,0,388,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
425354,425354,7291,4561,18,NaN,NaN,NaN,NaN
425355,425355,7291,4647,18,NaN,NaN,NaN,NaN
425356,425356,7291,4735,18,NaN,NaN,NaN,NaN
425357,425357,7291,4830,18,NaN,NaN,NaN,NaN
425358,425358,7291,4917,18,NaN,NaN,NaN,NaN

In [44]:
df_merge[df_merge["category_lstm"].notnull()][10500:10550]

,id,fragment_id,time_point,behavior_id,category_xgboost,category_lstm,category_bilstm_resnet,category_merge
33803,33803,584,2469,1,1.0,6.0,1.0,1.0
33804,33804,584,2552,1,1.0,6.0,1.0,1.0
33805,33805,584,2636,1,1.0,6.0,1.0,1.0
33806,33806,584,2720,1,1.0,6.0,1.0,1.0
33807,33807,584,2802,1,1.0,6.0,1.0,1.0
33808,33808,584,2885,1,6.0,6.0,1.0,6.0
33809,33809,584,2968,1,1.0,6.0,1.0,1.0
33810,33810,584,3051,1,1.0,6.0,1.0,1.0
33811,33811,584,3135,1,1.0,6.0,1.0,1.0
33812,33812,584,3218,1,1.0,6.0,1.0,1.0
33813,33813,584,3301,1,1.0,6.0,1.0,1.0
33814,33814,584,3385,1,1.0,6.0,1.0,1.0
33815,33815,584,3468,1,1.0,6.0,1.0,1.0
33816,33816,584,3552,1,1.0,6.0,1.0,1.0
33817,33817,584,3635,1,1.0,6.0,1.0,1.0
33818,33818,584,3719,1,1.0,6.0,1.0,1.0
33819,33819,584,3802,1,1.0,6.0,1.0,1.0
33820,33820,584,3885,1,1.0,6.0,1.0,1.0
33821,33821,584,3969,1,1.0,6.0,1.0,1.0
33822,33822,584,4052,1,1.0,6.0,1.0,1.0
33823,33823,584,4135,1,1.0,6.0,1.0,1.0
33824,33824,584,4218,1,1.0,6.0,1.0,1.0
33825,33825,584,4307,1,1.0,6.0,1.0,1.0
33826,33826,584,4385,1,1.0,6.0,1.0,1.0
33827,33827,584,4468,1,1.0,6.0,1.0,1.0
33828,33828,584,4552,1,1.0,6.0,1.0,1.0
33829,33829,584,4636,1,1.0,6.0,1.0,1.0
33830,33830,584,4720,1,1.0,6.0,1.0,1.0
33831,33831,584,4802,1,1.0,6.0,1.0,1.0
33832,33832,584,4885,1,1.0,6.0,1.0,1.0
33833,33833,584,4968,1,1.0,6.0,1.0,1.0
34433,34433,595,49,1,11.0,11.0,11.0,11.0
34434,34434,595,136,1,1.0,11.0,11.0,11.0
34435,34435,595,216,1,18.0,11.0,11.0,11.0
34436,34436,595,299,1,1.0,11.0,11.0,11.0
34437,34437,595,383,1,18.0,11.0,11.0,11.0
34438,34438,595,466,1,18.0,11.0,11.0,11.0
34439,34439,595,549,1,1.0,11.0,11.0,11.0
34440,34440,595,632,1,1.0,11.0,11.0,11.0
34441,34441,595,718,1,1.0,11.0,11.0,11.0
34442,34442,595,799,1,1.0,11.0,11.0,11.0
34443,34443,595,882,1,1.0,11.0,11.0,11.0
34444,34444,595,965,1,1.0,11.0,11.0,11.0
34445,34445,595,1049,1,1.0,11.0,11.0,11.0
34446,34446,595,1132,1,1.0,11.0,11.0,11.0
34447,34447,595,1217,1,1.0,11.0,11.0,11.0
34448,34448,595,1300,1,1.0,11.0,11.0,11.0
34449,34449,595,1383,1,1.0,11.0,11.0,11.0
34450,34450,595,1465,1,1.0,11.0,11.0,11.0
34451,34451,595,1550,1,1.0,11.0,11.0,11.0

In [45]:
y_true = df_merge[df_merge["category_lstm"].notnull()]["behavior_id"].values
y_pred = df_merge[df_merge["category_lstm"].notnull()]["category_merge"].values
acc = np.mean(np.equal(y_true, y_pred))
acc

0.6679077974414762